### ISSUE TITLE
binary doesn't open on windows

### ISSUE THREAD

**Issue by phanirithvij** [loov/zombieroom#3]
Binary doesn't open on windows when my joystick is connected (works with the mouse)
No errors on the console.

**Comment by egonelbre** [comment]
Can you try whether this release fixes it https://github.com/adinfinit/zombies-on-ice/releases/tag/v0.2.0? I bumped glfw and gl to the latest version, but I don't have any other ideas why it would fail.

**Comment by phanirithvij** [comment]
This issue was in the binary downloaded from readme v0.1 https://github.com/adinfinit/zombies-on-ice/releases/tag/v0.1,
It was working with the master branch before v0.2.0.

**Comment by phanirithvij** [comment]
It was becuase of this

```go
	axis := func(ix, iy int) g.V2 {
                // this line wasn't in v0.1 it's already fixed
		if ix >= len(axes) || iy >= len(axes) {
			return g.V2{}
		}
		return g.V2{
			X: g.ApplyDeadZone(axes[ix], gamepad.DeadZone),
			Y: -g.ApplyDeadZone(axes[iy], gamepad.DeadZone),
		}
	}
```
